version: "3.8"
services:
  app:
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - database
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  keycloak:
    build:
      context: ./config/keycloak
    # command: start-dev 
    environment:
      # KC Credentials
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_TEMP_ADMIN}  
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_TEMP_PASSWORD}  
      # KC Database Credentials
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database:5432/${KC_DB_NAME}
      - KC_DB_USERNAME=${KC_DB_USER}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KEYCLOAK_IMPORT=/opt/keycloak/imports/myrealm-config.json  # Add this line to ensure import
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Api DB Variables
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      # Keycloak DB variables
      - KC_DB_NAME=${KC_DB_NAME}     
      - KC_DB_USER=${KC_DB_USER}    
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}  
    volumes:
      - ./config/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro  
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database: